import { ColorSwatchIcon } from "@heroicons/react/outline";
import { DropdownValueProps } from "../MidJourneyPage";
import PopoutInput from "./PopoutInput";

const options = [
  "",
  "white",
  "black",
  "light gray",
  "dark gray",
  "maroon",
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "cyan",
  "teal",
  "blue",
  "indigo",
  "purple",
  "violet",
  "brown",
  "dark-maroon",
  "dark-red",
  "dark-orange",
  "dark-yellow",
  "dark-lime",
  "dark-green",
  "dark-cyan",
  "dark-teal",
  "dark-blue",
  "dark-indigo",
  "dark-purple",
  "dark-violet",
  "dark-brown",
  "light-maroon",
  "light-red",
  "light-orange",
  "light-yellow",
  "light-lime",
  "light-green",
  "light-cyan",
  "light-teal",
  "light-blue",
  "light-indigo",
  "light-purple",
  "light-violet",
  "light-brown",
  "black and white",
  "light color",
  "dark color",
  "sepia color",
  "complementary color",
  "cool color",
  "dichromatism color",
  "faded color",
  "inverted color",
  "muted color",
  "neon color",
  "pantone color",
  "pastel color",
  "rainbow color",
  "saturated color",
  "spectral solar",
  "vibrant color",
  "vivid color",
  "warm color",
  "high contrast",
  "low contrast",
  "RGB",
  "CMYK",
  "1-bit grayscale",
  "4-bit grayscale",
  "3-bit color",
  "6-bit color",
  "technicolor",
  "spring colors",
  "summer colors",
  "autumn colors",
  "winter colors",
  "gradient color",
  "pop-art color",
  "spectrum color",
  "synesthesia color",
  "purity color",
  "funky color",
  "disco color",
  "confetti color",
  "tie-dye color",
  "polka dot color",
  "halftone color",
  "camouflage color",
  "diffraction pattern color",
  "35mm film color",
  "agfacolor color",
  "ambrotype color",
  "bokeh color",
  "calotype color",
  "chromatic aberration color",
  "collodion glass plate color",
  "cyanotype color",
  "daguerreotype color",
  "depth map color",
  "expired film color",
  "expired polaroid",
  "film negative color",
  "fujifilm digital",
  "hyperspectral imaging color",
  "instax color",
  "kodachrome color",
  "kodak gold 200 film color",
  "lomography color",
  "night vision color",
  "photogram color",
  "polaroid color",
  "polaroid photograph color",
  "sepia photograph color",
  "tintype color",
  "tri-x 400 tx color",
  "ultraviolet color",
  "vignette color",
  "vintage film color",
  "1930s style color",
  "1950s style color",
  "1960s style color",
  "1970s style color",
  "1980s style color",
  "1990s style color",
  "retro color",
  "modern color",
  "vintage color",
  "antique color",
  "spring color",
  "summer color",
  "autumn color",
  "winter color",
];

const colorOptions = options.map((option) => {
  if (option === "") {
    return { label: "No Preference", command: "" };
  }
  return {
    label: option,
    command: option,
  };
});

export default function ColorSelector({
  value,
  setValue,
}: {
  value: DropdownValueProps | null;
  setValue: (value: DropdownValueProps | null) => void;
}) {
  return (
    <PopoutInput
      label="Color"
      icon={<ColorSwatchIcon />}
      value={value}
      setValue={setValue}
      options={colorOptions}
    />
  );
}
